-- Generated from client-provided Item List_View All.xlsx.
-- Raw materials consolidated where the source sheet tracked the same
-- physical ingredient as separate per-dish SKUs (see conversation notes).
-- Costs marked 'approximate' in comments should be confirmed by the owner
-- via the Raw Materials screen.

insert into item_categories (name, item_type) values
  ('Beef', 'raw_material'),
  ('Chicken', 'raw_material'),
  ('Dessert Ingredients', 'raw_material'),
  ('Dry Goods & Condiments', 'raw_material'),
  ('Frozen Foods', 'raw_material'),
  ('Fruits', 'raw_material'),
  ('Goat', 'raw_material'),
  ('Griller & Kitchen Supplies', 'raw_material'),
  ('Packaging & Operating Supplies', 'raw_material'),
  ('Pork', 'raw_material'),
  ('Seafood', 'raw_material'),
  ('Vegetables', 'raw_material'),
  ('Beverages', 'product'),
  ('Dessert', 'product'),
  ('Ice Cream (Freezer Retail)', 'product')
on conflict (name, item_type) do nothing;

insert into raw_materials (sku, name, category_id, unit_id, cost_per_unit, reorder_point) values
  ('SKU-PEANUT-BUTTER', 'Peanut Butter', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.205882, 0),
  ('SKU-PATATAS', 'Patatas', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.08, 0),
  ('SKU-KALDERETA-POWDER', 'Kaldereta Powder', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 1.0, 0),
  ('SKU-MANG-TOMAS-BOTTLE-11-46OZ', 'Mang Tomas Bottle 11.46oz', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'mL'), 0.118024, 0),
  ('SKU-TISSUE-PACK', 'Tissue Pack', (select id from item_categories where name = 'Packaging & Operating Supplies' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'pc'), 60.0, 0),
  ('SKU-TISSUE-BUNDLE', 'Tissue Bundle', (select id from item_categories where name = 'Packaging & Operating Supplies' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'pc'), 60.0, 0),
  ('SKU-SWEET-CHILI-SAUCE-3-2L-GALLON', 'Sweet Chili Sauce 3.2L Gallon', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.078125, 0),
  ('SKU-PATIS-BOTTLE-1L', 'Patis Bottle 1L', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'mL'), 0.07, 0),
  ('SKU-GULAMAN-SACHET', 'Gulaman Sachet', (select id from item_categories where name = 'Dessert Ingredients' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.7875, 0),
  ('SKU-JOLLY-MUSHROOM-PACK-100G', 'Jolly Mushroom Pack 100g', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.3, 0),
  ('SKU-CAJUN-POWDER-BOTTLE', 'Cajun Powder Bottle', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'pc'), 800.0, 0),
  ('SKU-CHICHARAP-REPACK', 'Chicharap Repack', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'pc'), 5.0, 0),
  ('SKU-FRIED-GARLIC-BAG-1KG', 'Fried Garlic Bag 1Kg', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.25, 0),
  ('SKU-SINIGANG-NA-SAMPALOK-BAG-1KG-SABAW', 'Sinigang na Sampalok Bag 1Kg (Sabaw)', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.5, 0),
  ('SKU-TAHONG', 'Tahong', (select id from item_categories where name = 'Seafood' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'pc'), 2.0, 0),
  ('SKU-BLOOD-COCKLES', 'Blood Cockles', (select id from item_categories where name = 'Seafood' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'pc'), 3.0, 0),
  ('SKU-GRILLED-SQUID-FOR-KAMAYAN-SPECIALTY', 'Grilled Squid for Kamayan & Specialty', (select id from item_categories where name = 'Seafood' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'pc'), 50.0, 0),
  ('SKU-CHICKEN-OIL', 'Chicken Oil', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'mL'), 0.109375, 0),
  ('SKU-ATSARA', 'Atsara', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.110132, 0),
  ('SKU-HONEY-BUTTER-SAUCE', 'Honey Butter Sauce', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.1192, 0),
  ('SKU-BUFFALO-SAUCE', 'Buffalo Sauce', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.113636, 0),
  ('SKU-TILAPIA-KAMAYAN', 'Tilapia (Kamayan)', (select id from item_categories where name = 'Seafood' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'pc'), 50.0, 0),
  ('SKU-VINEGAR-GALLON-3-2L', 'Vinegar Gallon 3.2L', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'mL'), 0.04375, 0),
  ('SKU-PAMINTA-BAG-1KG', 'Paminta Bag 1Kg', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.268, 0),
  ('SKU-VETSIN-BAG-5KG', 'Vetsin Bag 5kg', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.172, 0),
  ('SKU-KANGKONG', 'Kangkong', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.05, 0),
  ('SKU-BURO', 'Buro', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.2, 0),
  ('SKU-AGAMANG', 'Agamang', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.1, 0),
  ('SKU-ITLOG-MAALAT', 'Itlog Maalat', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'pc'), 17.0, 0),
  ('SKU-EGG', 'Egg', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'pc'), 9.0, 0),
  ('SKU-PANSIT-SEAFOODS-NEW-MENU', 'Pansit Seafoods New Menu', (select id from item_categories where name = 'Seafood' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'pc'), 160.0, 0),
  ('SKU-SEAFOOD-KARE-KARE-NEW-MENU', 'Seafood Kare Kare New Menu', (select id from item_categories where name = 'Seafood' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'pc'), 200.0, 0),
  ('SKU-LONGSILOG-ALL-DAY-BREAKFAST', 'Longsilog All Day Breakfast', (select id from item_categories where name = 'Frozen Foods' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'pc'), 33.0, 0),
  ('SKU-HOTSILOG-ALL-DAY-BREAKFAST', 'Hotsilog All Day Breakfast', (select id from item_categories where name = 'Frozen Foods' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'pc'), 33.0, 0),
  ('SKU-TOCILOG-ALL-DAY-BREAKFAST', 'Tocilog All Day Breakfast', (select id from item_categories where name = 'Frozen Foods' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'pc'), 35.0, 0),
  ('SKU-TAPSILOG-ALL-DAY-BREAKFAST', 'Tapsilog All Day Breakfast', (select id from item_categories where name = 'Frozen Foods' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'pc'), 35.0, 0),
  ('SKU-ULING-SACK', 'Uling Sack', (select id from item_categories where name = 'Griller & Kitchen Supplies' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'pc'), 350.0, 0),
  ('SKU-CHICKEN-INASAL-SAUCE-3L', 'Chicken Inasal Sauce 3L', (select id from item_categories where name = 'Griller & Kitchen Supplies' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.093333, 0),
  ('SKU-PORK-BBQ-10-PCS', 'Pork BBQ 10 PCS', (select id from item_categories where name = 'Pork' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'pc'), 15.0, 0),
  ('SKU-GRILLED-LIEMPO-3-PCS', 'Grilled Liempo 3 PCS', (select id from item_categories where name = 'Pork' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'pc'), 60.0, 0),
  ('SKU-SIZZLING-PORKCHOP-SIZZLERS', 'Sizzling Porkchop Sizzlers', (select id from item_categories where name = 'Pork' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'pc'), 45.0, 0),
  ('SKU-SIZZLING-SAUSAGE-SIZZLERS', 'Sizzling Sausage Sizzlers', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'pc'), 80.0, 0),
  ('SKU-BEEF-POWDER-BAG-1000-GRAMS', 'Beef Powder Bag 1000 Grams', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'pc'), 0.77, 0),
  ('SKU-MANTIKA-GALLON-REPACK-3L', 'Mantika Gallon Repack 3L', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'mL'), 0.025511, 0),
  ('SKU-MANIKA-CONTAINER-18L', 'Manika Container 18L', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'pc'), 1377.6, 0),
  ('SKU-MARGARINE-REPACK-250-GRAMS', 'Margarine Repack 250 Grams', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.393272, 0),
  ('SKU-YOUNG-CORN', 'Young Corn', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.1, 0),
  ('SKU-BREADING-MIX-PACK-1-KG', 'Breading Mix Pack 1 Kg', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.07, 0),
  ('SKU-ATSUETE-PACK-125-GRAMS', 'Atsuete Pack 125 Grams', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.416, 0),
  ('SKU-BIHON-PACK-450-GRAMS', 'Bihon Pack 450 Grams', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.08, 0),
  ('SKU-SUGAR-PACK-1KG', 'Sugar Pack 1Kg', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.22472, 0),
  ('SKU-FLOUR-PACK-1-KG', 'Flour Pack 1 Kg', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.0288, 0),
  ('SKU-ASIN-1-KILO', 'Asin 1 Kilo', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.03, 0),
  ('SKU-RICE-SACK-25KG', 'Rice Sack 25kg', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.052, 0),
  ('SKU-KARE-KARE-MIX-PACK-57-GRAMS', 'Kare Kare Mix Pack 57 Grams', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.642105, 0),
  ('SKU-MAGIC-SARAP-PACK-800-GRAMS', 'Magic Sarap Pack 800 Grams', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.299925, 0),
  ('SKU-SINIGANG-NA-GABI-SACHET-22-GRAMS', 'Sinigang na Gabi Sachet 22 Grams', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.530454, 0),
  ('SKU-JERSEY-CONDENSE-MILK-CAN-390-GRAMS', 'Jersey Condense Milk Can 390 Grams', (select id from item_categories where name = 'Dessert Ingredients' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.098846, 0),
  ('SKU-JERSEY-MILK-EVAP-CAN-370ML', 'Jersey Milk Evap Can 370ml', (select id from item_categories where name = 'Dessert Ingredients' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'mL'), 0.077702, 0),
  ('SKU-DIP-SOY-SAUCE-GALLON-3-2L', 'Dip Soy Sauce Gallon 3.2L', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'mL'), 0.033437, 0),
  ('SKU-SUPREME-SOY-SAUCE-GALLON-3-2L', 'Supreme Soy Sauce Gallon 3.2L', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'mL'), 0.021718, 0),
  ('SKU-WHOLE-KENNEL-CORN-CAN-250-GRAMS', 'Whole Kennel Corn Can 250 Grams', (select id from item_categories where name = 'Dessert Ingredients' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.14668, 0),
  ('SKU-OYSTER-SAUCE-SACHET-30-GRAMS', 'Oyster Sauce Sachet 30 Grams', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.191666, 0),
  ('SKU-TOMATO-PASTE-PACK-70-GRAMS', 'Tomato Paste Pack 70 Grams', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.271428, 0),
  ('SKU-BAGOONG-BOTTLE-12OZ', 'Bagoong Bottle 12oz', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'mL'), 0.039449, 0),
  ('SKU-ALL-PURPOSE-CREAMER-PACK-250-ML', 'All Purpose Creamer Pack 250 ml', (select id from item_categories where name = 'Dry Goods & Condiments' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'mL'), 0.183319, 0),
  ('SKU-UBE-HALAYA-JAR-32OZ', 'Ube Halaya Jar 32oz', (select id from item_categories where name = 'Dessert Ingredients' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.149914, 0),
  ('SKU-UBE-HALAYA-JAR-12OZ', 'Ube Halaya Jar 12oz', (select id from item_categories where name = 'Dessert Ingredients' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.199885, 0),
  ('SKU-NATA-JAR-32OZ', 'Nata Jar 32oz', (select id from item_categories where name = 'Dessert Ingredients' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.125663, 0),
  ('SKU-NATA-JAR-12OZ', 'Nata Jar 12oz', (select id from item_categories where name = 'Dessert Ingredients' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.167551, 0),
  ('SKU-KAONG-JAR-32OZ', 'Kaong Jar 32oz', (select id from item_categories where name = 'Dessert Ingredients' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.152118, 0),
  ('SKU-KAONG-JAR-12OZ', 'Kaong Jar 12oz', (select id from item_categories where name = 'Dessert Ingredients' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.202825, 0),
  ('SKU-RED-MONGGO-JAR-12OZ', 'Red Monggo Jar 12oz', (select id from item_categories where name = 'Dessert Ingredients' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.205764, 0),
  ('SKU-RED-MONGGO-JAR-32OZ', 'Red Monggo Jar 32oz', (select id from item_categories where name = 'Dessert Ingredients' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.154323, 0),
  ('SKU-WHITE-BEANS-JAR-12OZ', 'White Beans Jar 12oz', (select id from item_categories where name = 'Dessert Ingredients' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.205764, 0),
  ('SKU-WHITE-BEANS-JAR-32OZ', 'White Beans Jar 32oz', (select id from item_categories where name = 'Dessert Ingredients' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.154323, 0),
  ('SKU-GARBANZOS-JAR-12OZ', 'Garbanzos Jar 12oz', (select id from item_categories where name = 'Dessert Ingredients' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.220462, 0),
  ('SKU-GARBANZOS-JAR-32OZ', 'Garbanzos Jar 32oz', (select id from item_categories where name = 'Dessert Ingredients' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.165346, 0),
  ('SKU-LANGKA-JAR-12OZ', 'Langka Jar 12oz', (select id from item_categories where name = 'Dessert Ingredients' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.308647, 0),
  ('SKU-LANGKA-JAR-32OZ', 'Langka Jar 32oz', (select id from item_categories where name = 'Dessert Ingredients' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.231485, 0),
  ('SKU-COCONUT-STRINGS-JAR-12OZ', 'Coconut Strings Jar 12oz', (select id from item_categories where name = 'Dessert Ingredients' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.220462, 0),
  ('SKU-COCONUT-STRING-JAR-32OZ', 'Coconut String Jar 32oz', (select id from item_categories where name = 'Dessert Ingredients' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.165346, 0),
  ('SKU-MANGGA', 'Mangga', (select id from item_categories where name = 'Fruits' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.08, 0),
  ('SKU-PAPAYA', 'Papaya', (select id from item_categories where name = 'Fruits' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.05, 0),
  ('SKU-PIPINO', 'Pipino', (select id from item_categories where name = 'Fruits' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.13, 0),
  ('SKU-SINGKAMAS', 'Singkamas', (select id from item_categories where name = 'Fruits' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.05, 0),
  ('SKU-WATERMELON-FRUIT', 'Watermelon Fruit', (select id from item_categories where name = 'Fruits' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.16, 0),
  ('SKU-PATOLA', 'Patola', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.14, 0),
  ('SKU-AMPALAYA', 'Ampalaya', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.14, 0),
  ('SKU-BUNGA-MALUNGGAY', 'Bunga Malunggay', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.08, 0),
  ('SKU-SIBUYAS', 'Sibuyas', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.17, 0),
  ('SKU-BAWANG', 'Bawang', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.12, 0),
  ('SKU-LUYA', 'Luya', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.14, 0),
  ('SKU-SAMPI-SAMPI', 'Sampi-sampi', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.2, 0),
  ('SKU-BUNGA-SINGKAMAS', 'Bunga Singkamas', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.035, 0),
  ('SKU-PARDA', 'Parda', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.2, 0),
  ('SKU-CALAMANSI', 'Calamansi', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.13, 0),
  ('SKU-SILI-RED', 'Sili Red', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.45, 0),
  ('SKU-SILI-GREEN', 'Sili Green', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.12, 0),
  ('SKU-KAMATIS', 'Kamatis', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.12, 0),
  ('SKU-TALONG', 'Talong', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.13, 0),
  ('SKU-OKRA', 'Okra', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.13, 0),
  ('SKU-SITAW', 'Sitaw', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.16, 0),
  ('SKU-KARDIS', 'Kardis', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.35, 0),
  ('SKU-PATANI', 'Patani', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.2, 0),
  ('SKU-KAMOTE', 'Kamote', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.06, 0),
  ('SKU-KALABASA', 'Kalabasa', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.07, 0),
  ('SKU-UMBOK', 'Umbok', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.04, 0),
  ('SKU-CAULI-FLOWER', 'Cauli Flower', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.1, 0),
  ('SKU-BELL-PEPPER', 'Bell Pepper', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.35, 0),
  ('SKU-SAYOTE', 'Sayote', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.12, 0),
  ('SKU-CHICHARO', 'Chicharo', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.35, 0),
  ('SKU-ONION-LEAVES', 'Onion Leaves', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.16, 0),
  ('SKU-CABBAGE', 'Cabbage', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.09, 0),
  ('SKU-BAGUIO-BEANS', 'Baguio Beans', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.2, 0),
  ('SKU-BROCCOLI', 'Broccoli', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.15, 0),
  ('SKU-CARROT', 'Carrot', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.13, 0),
  ('SKU-BANGUS-STEAK-SPECIALTY', 'Bangus Steak Specialty', (select id from item_categories where name = 'Seafood' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'pc'), 170.0, 0),
  ('SKU-CALAMARES-SPECIALTY', 'Calamares Specialty', (select id from item_categories where name = 'Seafood' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'pc'), 150.0, 0),
  ('SKU-CHICHARON-BULAKLAK-SPECIALTY', 'Chicharon Bulaklak Specialty', (select id from item_categories where name = 'Pork' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'pc'), 100.0, 0),
  ('SKU-FRIED-HITO-FOR-SPECIALTY-KAMAYAN', 'Fried Hito for Specialty & Kamayan', (select id from item_categories where name = 'Seafood' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'pc'), 100.0, 0),
  ('SKU-CHOPSUEY-SEAFOODS-SPECIALTY', 'Chopsuey Seafoods Specialty', (select id from item_categories where name = 'Seafood' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'pc'), 150.0, 0),
  ('SKU-MIXED-SEAFOODS-SPECIALTY', 'Mixed Seafoods Specialty', (select id from item_categories where name = 'Seafood' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'pc'), 235.0, 0),
  ('SKU-CRISPY-HIPON-SPECIALTY', 'Crispy Hipon Specialty', (select id from item_categories where name = 'Seafood' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'pc'), 90.0, 0),
  ('SKU-CRISPY-PATA-SPECIALTY', 'Crispy Pata Specialty', (select id from item_categories where name = 'Pork' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'pc'), 300.0, 0),
  ('SKU-SINIGANG-NA-SALMON-HEAD-SPECIALTY', 'Sinigang na Salmon Head Specialty', (select id from item_categories where name = 'Seafood' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'pc'), 80.0, 0),
  ('SKU-SIGARILYAS', 'Sigarilyas', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.26, 0),
  ('SKU-YELLOW-CORN', 'Yellow Corn', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.06, 0),
  ('SKU-PUSO-NG-SAGING', 'Puso ng Saging', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.07, 0),
  ('SKU-PECHAY', 'Pechay', (select id from item_categories where name = 'Vegetables' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.1, 0),
  ('SKU-LEMON', 'Lemon', (select id from item_categories where name = 'Fruits' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.1, 0),
  -- Cost/gram across source rows ranged 0.42-0.70; used 0.60 (Lechon Kawali Specialty row). Confirm actual supplier cost.
  ('SKU-LECHON-KAWALI-FRIED-PORK-BELLY', 'Lechon Kawali (Fried Pork Belly)', (select id from item_categories where name = 'Pork' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.6, 0),
  -- Cost/piece from Chicken Inasal 40pc bag (₱2,700/40). Confirm against current supplier invoice.
  ('SKU-CLQ-MARINATED-CHICKEN-LEG-QUARTER', 'CLQ (Marinated Chicken Leg Quarter)', (select id from item_categories where name = 'Chicken' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'pc'), 67.5, 0),
  -- Averaged from two source rows (0.67-0.83/g). Confirm actual cost.
  ('SKU-BULALO-BEEF-SHANK-BONE-MARROW', 'Bulalo (Beef Shank/Bone Marrow)', (select id from item_categories where name = 'Beef' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.75, 0),
  -- Averaged from two source rows (0.60-0.83/g). Confirm actual cost.
  ('SKU-BEEF-SLICED-FOR-STIR-FRY', 'Beef (Sliced, for stir-fry)', (select id from item_categories where name = 'Beef' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.72, 0),
  -- Averaged from three source rows (0.64-0.87/g). Confirm actual cost.
  ('SKU-GOAT-MEAT-KAMBING', 'Goat Meat (Kambing)', (select id from item_categories where name = 'Goat' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.78, 0),
  -- Per-piece cost varied widely (55-100). Confirm actual current supplier cost.
  ('SKU-BANGUS-MILKFISH-WHOLE', 'Bangus (Milkfish, Whole)', (select id from item_categories where name = 'Seafood' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'pc'), 81.25, 0),
  -- Consistent across both source rows (12.5/pc). High confidence.
  ('SKU-HIPON-SHRIMP', 'Hipon (Shrimp)', (select id from item_categories where name = 'Seafood' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'pc'), 12.5, 0),
  -- Averaged from two source rows (0.75-0.80/g). Confirm actual cost.
  ('SKU-TUNA', 'Tuna', (select id from item_categories where name = 'Seafood' and item_type = 'raw_material'), (select id from units_of_measure where abbreviation = 'g'), 0.77, 0)
on conflict (sku) do nothing;

insert into products (sku, name, category_id, unit_id, price) values
  ('SKU-3N1-VANILLA-CHOCOLATE-STRAWBERRY-1-5L', '3n1 Vanilla, Chocolate, Strawberry 1.5L', (select id from item_categories where name = 'Ice Cream (Freezer Retail)' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-2N1-AVOCADO-STRAWBERRY-SUNDAE', '2n1 Avocado/Strawberry Sundae', (select id from item_categories where name = 'Ice Cream (Freezer Retail)' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-SORBETES-3N1-800ML', 'Sorbetes 3n1 800ml', (select id from item_categories where name = 'Ice Cream (Freezer Retail)' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-VANILLA-NUT-CHUNKY-CUP', 'Vanilla Nut Chunky Cup', (select id from item_categories where name = 'Ice Cream (Freezer Retail)' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-VANILLA-BERRY-SUNDAE', 'Vanilla berry Sundae', (select id from item_categories where name = 'Ice Cream (Freezer Retail)' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-CHOCOLATE-SUNDAE', 'Chocolate Sundae', (select id from item_categories where name = 'Ice Cream (Freezer Retail)' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-BINGO-CONE', 'Bingo Cone', (select id from item_categories where name = 'Ice Cream (Freezer Retail)' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-STRAWBERRY-CONE', 'Strawberry Cone', (select id from item_categories where name = 'Ice Cream (Freezer Retail)' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-CHOCO-MELT', 'Choco Melt', (select id from item_categories where name = 'Ice Cream (Freezer Retail)' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-DOUBLE-CHOCOLATE-CRISPY', 'Double Chocolate Crispy', (select id from item_categories where name = 'Ice Cream (Freezer Retail)' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-CHOCOLATE-CRISPY', 'Chocolate Crispy', (select id from item_categories where name = 'Ice Cream (Freezer Retail)' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-TARO-CRISPY', 'Taro Crispy', (select id from item_categories where name = 'Ice Cream (Freezer Retail)' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-COFFEE-CRISPY', 'Coffee Crispy', (select id from item_categories where name = 'Ice Cream (Freezer Retail)' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-STRAWBERRY-CRISPY', 'Strawberry Crispy', (select id from item_categories where name = 'Ice Cream (Freezer Retail)' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-SWEET-CORN', 'Sweet Corn', (select id from item_categories where name = 'Ice Cream (Freezer Retail)' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-2-COLORS', '2 Colors', (select id from item_categories where name = 'Ice Cream (Freezer Retail)' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-FRUITY-ROLL', 'Fruity Roll', (select id from item_categories where name = 'Ice Cream (Freezer Retail)' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-MOCHI-VANILLA', 'Mochi Vanilla', (select id from item_categories where name = 'Ice Cream (Freezer Retail)' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-MOCHI-CHOCO', 'Mochi Choco', (select id from item_categories where name = 'Ice Cream (Freezer Retail)' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-MILK-MELON', 'Milk Melon', (select id from item_categories where name = 'Ice Cream (Freezer Retail)' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-TROPEEKA-MANGO-CONATA', 'Tropeeka Mango Conata', (select id from item_categories where name = 'Ice Cream (Freezer Retail)' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-CEREAL-MILK-CRISPY', 'Cereal Milk Crispy', (select id from item_categories where name = 'Ice Cream (Freezer Retail)' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-ORANGE', 'Orange', (select id from item_categories where name = 'Ice Cream (Freezer Retail)' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-PINEAPPLE', 'Pineapple', (select id from item_categories where name = 'Ice Cream (Freezer Retail)' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-WATERMELON', 'Watermelon', (select id from item_categories where name = 'Ice Cream (Freezer Retail)' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-MIKI-MIKI-CHOCO', 'Miki Miki Choco', (select id from item_categories where name = 'Ice Cream (Freezer Retail)' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-MIKI-MIKI', 'Miki Miki', (select id from item_categories where name = 'Ice Cream (Freezer Retail)' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-MILK-STICK', 'Milk Stick', (select id from item_categories where name = 'Ice Cream (Freezer Retail)' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-CHOCO-MALT', 'Choco Malt', (select id from item_categories where name = 'Ice Cream (Freezer Retail)' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-CHOCOLATE-STICK', 'Chocolate Stick', (select id from item_categories where name = 'Ice Cream (Freezer Retail)' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-LECHE-FLAN-DESSERT', 'Leche Flan (Dessert)', (select id from item_categories where name = 'Dessert' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-RC-COLA-PRODUCTS-1-5L-UNLI', 'RC Cola Products 1.5L (UNLI)', (select id from item_categories where name = 'Beverages' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'mL'), 0),
  ('SKU-ALFONSO-1L-BOTTLE', 'Alfonso 1L Bottle', (select id from item_categories where name = 'Beverages' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-MOJITO-1L-BOTTLE', 'Mojito 1L Bottle', (select id from item_categories where name = 'Beverages' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-ICE-CREAM-BUKO-1-9L-GALLON', 'Ice Cream Buko 1.9L Gallon', (select id from item_categories where name = 'Dessert' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-ICE-CREAM-UBE-1-9L-GALLON', 'Ice Cream Ube 1.9L Gallon', (select id from item_categories where name = 'Dessert' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-TASTY-PALAMIG-PACK-500-GRAMS', 'Tasty Palamig Pack 500 Grams', (select id from item_categories where name = 'Beverages' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'g'), 0),
  ('SKU-ICE-CREAM-ASSORTED-GALLON-1-9L', 'Ice Cream Assorted Gallon 1.9L', (select id from item_categories where name = 'Dessert' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-ICE-CREAM-ASSORTED', 'Ice Cream Assorted', (select id from item_categories where name = 'Dessert' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-ICE-CREAM-UBE-2-2L-TUB', 'Ice Cream Ube 2.2L Tub', (select id from item_categories where name = 'Dessert' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'mL'), 0),
  ('SKU-ICE-CREAM-BUKO-2-2L-TUB', 'Ice Cream Buko 2.2L Tub', (select id from item_categories where name = 'Dessert' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'mL'), 0),
  ('SKU-GLAZIER-WATER-BOTTLE-350-ML', 'Glazier Water Bottle 350 ml', (select id from item_categories where name = 'Beverages' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-LECHE-FLAN-TUB-HALO-HALO', 'Leche Flan Tub (Halo halo)', (select id from item_categories where name = 'Dessert' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'g'), 0),
  ('SKU-RC-COLA-PRODUCTS-BOTTLE-1-5L', 'RC Cola Products Bottle 1.5L', (select id from item_categories where name = 'Beverages' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-RC-COLA-PRODUCTS-BOTTLE-8OZ', 'RC Cola Products Bottle 8oz', (select id from item_categories where name = 'Beverages' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-SAN-MIGUEL-RED-HORSE-STALLION-BOTTLE-330ML', 'San Miguel Red Horse Stallion Bottle 330ml', (select id from item_categories where name = 'Beverages' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-SAN-MIGUEL-PALE-PILSEN-BOTTLE-330ML', 'San Miguel Pale Pilsen Bottle 330ml', (select id from item_categories where name = 'Beverages' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0),
  ('SKU-SAN-MIGUEL-LIGHTS-BOTTLE-330ML', 'San Miguel Lights Bottle 330ml', (select id from item_categories where name = 'Beverages' and item_type = 'product'), (select id from units_of_measure where abbreviation = 'pc'), 0)
on conflict (sku) do nothing;